### ISSUE TITLE
BUG: requirements.txt needs to be updated

### ISSUE THREAD

**Issue by wujiahao15** [NASA-NJU/FlyMon#15]
## Problem

1. Creating a pure virtual environment with python version `3.8.10`.
2. Using `pip install -r requirements.txt` command to install python dependencies.
3. I got the following error message when using `flymon_compiler.py` to generate data plane codes.

![image](https://user-images.githubusercontent.com/22017865/184637692-48d75abb-9eb3-4fb4-8ad1-d1feef114afc.png)

## Reason

* After digging in this problem, I found the following:
  * `jinja2` replies on the package called `markupsafe`.
  * `jinja2` version in the `requirements.txt` is inconsistent with `markupsafe` package.
    * `markupsafe` package removes `soft_unicode` in version `2.1.0`, which is a breaking change to `jinja2`.

## Solution

* Upgrading `jinja2` package to the latest version works for me.
  * Now that `jinja2` version is `3.1.2`.

**Comment by mmhzheng** [comment]
Thanks! I am working on the dev branch to refactor the existing codes. I will merge your pull request after the refactoring is done.

**Comment by wujiahao15** [comment]
> Thanks! I am working on the dev branch to refactor the existing codes. I will merge your pull request after the refactoring is done.

Both your python codes and p4 codes are really pretty! If you can add [type annotations](https://docs.python.org/3/library/typing.html) of parameters and return types in python codes, I think the codes will become more readable and be easier to maintain than before.

I feel privileged to participate in improving this project.

**Comment by mmhzheng** [comment]
Thank you for your suggestions. I will gradually add type annotations to the code.
