### ISSUE TITLE
Can not execute run_controller.sh

### ISSUE THREAD

**Issue by SdotChen** [NASA-NJU/FlyMon#17]
![image](https://user-images.githubusercontent.com/40907552/185608634-8a7e55c7-c28c-4613-8ad4-01b2e2194194.png)
Is it about the version of JinJa2?

**Comment by mmhzheng** [comment]
Hi~ The control-plane codes use the f-string feature of Python3 (specially, Python 3.6+). What's your Python's version?

**Comment by SdotChen** [comment]
> Hi~ The control-plane codes use the f-string feature of Python3 (specially, Python 3.6+). What's your Python's version?

I have tried by both python 2.7 and python 3.5 but failed. So I downloaded and installed Python 3.8, but it still went wrong.
![image](https://user-images.githubusercontent.com/40907552/185731483-409cc94c-7745-4e00-8141-4c9f71f1561c.png)

**Comment by mmhzheng** [comment]
Bfrt modules are required for the control plane, you should let your Python know the path of these modules. As you can seen in the "control_plane/run_controller.sh", I extend several $PYPATH environments variables. You should check if the PATHs of the environments variables are valid in your environments.
I think the most likely problem is that your $SDE variable is not set correctly.

**Comment by SdotChen** [comment]
> Bfrt modules are required for the control plane, you should let your Python know the path of these modules. As you can seen in the "control_plane/run_controller.sh", I extend several $PYPATH environments variables. You should check if the PATHs of the environments variables are valid in your environments. I think the most likely problem is that your $SDE variable is not set correctly.

I set my $SDE variable in .bashrc so it will be set after each reboot. Maybe my SDE version is 9.2, there is no `python3.8` directory in $SDE/install/lib, but I see it in SDE 9.7. It seems that only the compilation and entrance to bfshell are accessible in the implementation of SDE 9.2. Thank you for your answering and I will have an another try in SDE 9.7.
